spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pips?useSSL=true&useUnicode=true&characterEncoding=UTF-8"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /**